; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
    sinricpro/SinricPro@^2.9.4
    links2004/WebSockets@^2.3.5
    bblanchon/ArduinoJson@^6.12.0
 
# Inject build flags from environment variables. Use the `scripts/load_env_and_build.py`
# wrapper to load values from a local `.env` file into the build environment.
build_flags =
    -D WIFI_SSID=\"${env.WIFI_SSID}\"
    -D WIFI_PASS=\"${env.WIFI_PASS}\"
    -D APP_KEY=\"${env.APP_KEY}\"
    -D APP_SECRET=\"${env.APP_SECRET}\"
    -D DEVICE_ID_1=\"${env.DEVICE_ID_1}\"
    -D DEVICE_ID_2=\"${env.DEVICE_ID_2}\"
    -D DEVICE_ID_3=\"${env.DEVICE_ID_3}\"
